//
// The OpenIsolation Project
//

/**
  Symbols:
  FILE_PACKER::file_interface_callback(STREAMED_FILE_HANDLE*, STREAMED_FILE_STATE, void*)
  FILE_PACKER::FILE_INTERFACE_STREAMABLE::~FILE_INTERFACE_STREAMABLE()
  FILE_PACKER::FILE_INTERFACE_STREAMABLE::~FILE_INTERFACE_STREAMABLE()
  FILE_PACKER::FILE_INTERFACE_STREAMABLE::service_next_request()
  FILE_PACKER::PACKED_FILE_READABLE::get_file_interface()
  FILE_PACKER::PACKED_FILE_READABLE::~PACKED_FILE_READABLE()
  FILE_PACKER::PACKED_FILE_READABLE::~PACKED_FILE_READABLE()
  GCC_except_table5
  GCC_except_table6
  GCC_except_table13
  GCC_except_table14
  typeinfo name for FILE_PACKER::FILE_INTERFACE_STREAMABLE
  typeinfo name for FILE_PACKER::PACKED_FILE_READABLE
  vtable for FILE_PACKER::FILE_INTERFACE_STREAMABLE
  typeinfo for FILE_PACKER::FILE_INTERFACE_STREAMABLE
  vtable for FILE_PACKER::PACKED_FILE_READABLE
  typeinfo for FILE_PACKER::PACKED_FILE_READABLE
*/
