//
// The OpenIsolation Project
//

/// Enum of all supported setting types in the engine.
enum class eSettingType {
  DEPTH_OF_FIELD = 0,
  LEVEL_OF_DETAIL,
  DEEP_COLOUR_30BPP,
  FULLSCREEN_RES_24BPP,
  FULLSCREEN_RES_30BPP,
  WINDOWED_RES,
  FULLSCREEN,
  VERTICAL_SYNC,
  PARTICLES,
  ANTI_ALIASING,
  GRAPHICS,
  SHADOW_MAP_RES,
  SHADOW_MAPPING,
  MOTION_BLUR,
  CHROMATIC_ABERRATION,
  FILM_GRAIN_INTENSITY,
  PLANAR_REFLECTIONS,
  FIELD_OF_VIEW,
  VOLUMETRIC_LIGHTING,
  STREAMING_TEXTURE_HEAP_SIZE,
  STREAMING_MODEL_HEAP_SIZE,
  SCREEN_SPACE_AMBIENT_OCCLUSION,
  TEXTURE_FILTERING,
  MULTITHREADED_SHADOW_RENDERING,
  STEREO_MODE,
  AUDIO,
  SFX_VOLUME,
  MUSIC_VOLUME,
  SPEAKER_MODE,
  DUALSHOCK_SPEAKER,
  AUDIO_LANGUAGE,
};
